apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetme
  labels:
    app: greetme
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: greetme
  template:
    metadata:
      labels:
        app: greetme
    spec:
      containers:
        - name: greetme
          image: ssen96/greetme:latest  # Image from Docker Hub
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"

